### ISSUE TITLE
Cohort selection limited to 25 cohorts

### ISSUE THREAD

**Issue by jtsafran** [moodle-an-hochschulen/moodle-availability_cohort#2]
The use of `cohort_get_available_cohorts($context);` in frontend.php (https://github.com/moodleuulm/moodle-availability_cohort/blob/master/classes/frontend.php#L87) only returns 25 cohorts by default.  See the function definition at Moodle: https://github.com/moodle/moodle/blob/MOODLE_35_STABLE/cohort/lib.php#L239

I'm not sure what makes the most sense here for a fix, be it some hardcoded limit, or maybe something that you could have an end user set in a setting?  Thoughts?

For the case we are using this, we hardcoded it to 1000.  The call was changed to:

`return cohort_get_available_cohorts($context, 0, 0, 1000);`

**Comment by abias** [comment]
Hi @jtsafran ,

thank you for raising this issue and sorry for the late reply.

Your reported issue is valid, we just didn't realize this limitation yet as we don't have more than 25 cohorts in production.

As far I see, `cohort_get_available_cohorts()` passes the limit parameter to `$DB->get_records_sql()`
(see https://github.com/moodle/moodle/blob/MOODLE_35_STABLE/cohort/lib.php#L315). And `$DB->get_records_sql()` also supports a limit of 0 which is also the function's default (see https://github.com/moodle/moodle/blob/MOODLE_35_STABLE/lib/dml/moodle_database.php#L1417).

So, my natural conclusion would be that we should change
`return cohort_get_available_cohorts($context);`
to
`return cohort_get_available_cohorts($context, 0, 0, 0);`

The only downside would be that this change would slow down each activity editing page (where the function is called by the plugin during availability condition initialization) a little bit for installations with huge numbers of cohorts as cohort_get_available_cohorts() does not use any caches at the moment.

Could you double-check if 
`return cohort_get_available_cohorts($context, 0, 0, 0);`
would also work for the case where you are using this?

As soon as confirmed successfully, we would fix this in the plugin.

Thanks,
Alex

**Comment by jtsafran** [comment]
Alex,

That would work here, for sure.  I can't think of any cases where we have cohort numbers over 500-1000 and I think most DBs that are already handling that many cohorts can handle that many queries without significant impact.

The only other option I see would be to have a front end option in the settings that allows you to pick the limit.  Either way fixes the problem and works for us!

Thanks for the awesome plugin!
-Jesse

**Comment by Kathrin84** [comment]
Hi @jtsafran,

finally I had time to address this issue. :)

We've decided to use the "unlimited" option and not add another setting to be able to set the limit manually. The main reason is that the limit is designed to be used with pagination functionality. And within the dropdown this is not possible.
So if you would set the limit for example to 32 cohorts but you have 40 cohorts the same affect would occur. You would only get the first 32 cohorts and the last 8 not. So although the list can get really long, we don't see any better solution currently than to use the "unlimited" option.

The patch: https://github.com/moodleuulm/moodle-availability_cohort/commit/7bc2f46a2ddd78a63739c890370f84d6f8b46dc8

We will also directly release a new version of the plugin in the Moodle plugin's repo.

As this issue is fixed, I'll close it and thank you very much again for raising this issue.

Best, Kathrin

**Comment by jtsafran** [comment]
Thank you so much for the fix and the great plugin!
